### ISSUE TITLE
Feature request: Post resolution only

### ISSUE THREAD

**Issue by LJWatson** [dbaron/wgmeeting-github-ircbot#51]
We've begun experimenting with the bot for AB meetings and for reasons it would be useful if the bot could be instructed to post only the resolution for a topic instead of all the related chat log. 

We realise it's technically possible to do this now by only invoking the bot at the point a resolution is recorded in IRC, but this then plays havoc with the published minutes because the heading structure gets all out of flow with the content.

**Comment by dbaron** [comment]
Sorry, I managed to forget about this.  I just implemented it, although I didn't test the fix at all, so you should test it to make sure it works.

That said, I can't actually restart the bot now since the cert for `irc.w3.org` is currently expired, so if I restart it it will fail to connect.  So you can't test it until after I restart the bot.

**Comment by dbaron** [comment]
(I should really add an automated test at some point; it shouldn't be too hard.)
